use_field_init_shorthand = true
newline_style = "Unix"

# The following lines may be uncommented on nightly Rust.
unstable_features = true
imports_granularity = "Crate"
wrap_comments = true
comment_width = 100
normalize_comments = true
